import {
  NextResponse,
} from "next/server";

import path from "node:path";
import fs from "node:fs/promises";
import crypto from "node:crypto";

import {
  ensureWorkspaceRoot,
  getAssetWorkspace,
  removeWorkspace,
} from "../../../../lib/server/workspaces/workspace";

export const runtime = "nodejs";

const MAX_UPLOAD_BYTES =
  1024 * 1024 * 1024;

function createWorkspaceId() {
  return (
    "WS-" +
    Date.now()
      .toString(36)
      .toUpperCase() +
    "-" +
    crypto
      .randomBytes(4)
      .toString("hex")
      .toUpperCase()
  );
}

function looksLikeTar(
  buffer: Buffer
): boolean {
  /*
   * POSIX TAR archives normally contain
   * "ustar" at offset 257.
   *
   * Docker image archives generated by
   * docker save use TAR format.
   */
  if (buffer.length < 512) {
    return false;
  }

  const magic =
    buffer
      .subarray(257, 262)
      .toString("ascii");

  return magic === "ustar";
}

export async function POST(
  request: Request
) {
  let workspaceId:
    | string
    | undefined;

  try {
    const formData =
      await request.formData();

    const uploaded =
      formData.get("file");

    if (
      !(uploaded instanceof File)
    ) {
      return NextResponse.json(
        {
          error:
            "A Docker/OCI TAR archive is required.",
        },
        {
          status: 400,
        }
      );
    }

    if (uploaded.size <= 0) {
      return NextResponse.json(
        {
          error:
            "Uploaded container archive is empty.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      uploaded.size >
      MAX_UPLOAD_BYTES
    ) {
      return NextResponse.json(
        {
          error:
            "Container archive exceeds the 1 GB upload limit.",
        },
        {
          status: 413,
        }
      );
    }

    if (
      path
        .extname(uploaded.name)
        .toLowerCase() !== ".tar"
    ) {
      return NextResponse.json(
        {
          error:
            "Only Docker/OCI TAR archives are supported.",
        },
        {
          status: 415,
        }
      );
    }

    const buffer =
      Buffer.from(
        await uploaded.arrayBuffer()
      );

    if (!looksLikeTar(buffer)) {
      return NextResponse.json(
        {
          error:
            "Uploaded file is not a valid TAR archive.",
        },
        {
          status: 415,
        }
      );
    }

    await ensureWorkspaceRoot();

    workspaceId =
      createWorkspaceId();

    const workspace =
      getAssetWorkspace(
        workspaceId
      );

    const containerDirectory =
      path.join(
        workspace,
        "container"
      );

    await fs.mkdir(
      containerDirectory,
      {
        recursive: true,
      }
    );

    const archivePath =
      path.join(
        containerDirectory,
        "image.tar"
      );

    /*
     * Store the archive as an opaque artifact.
     *
     * Do not extract it.
     * Do not docker load it.
     * Do not execute it.
     */
    await fs.writeFile(
      archivePath,
      buffer
    );

    return NextResponse.json(
      {
        data: {
          workspaceId,
          originalName:
            uploaded.name,
          uploadSize:
            uploaded.size,
          containerArchivePath:
            archivePath,
        },
      },
      {
        status: 201,
      }
    );
  } catch (error) {
    if (workspaceId) {
      await removeWorkspace(
        workspaceId
      ).catch(() => {});
    }

    console.error(
      "[AppSecGate] Container archive upload failed:",
      error
    );

    return NextResponse.json(
      {
        error:
          "Unable to process container archive.",
      },
      {
        status: 500,
      }
    );
  }
}
